CREATE TABLE Events (
Event_ID INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
Time_Date TEXT(40) DEFAULT NULL,
Action_ID_Actions INTEGER NOT NULL  REFERENCES Actions (Action_ID),
Location_ID_Location INTEGER NOT NULL  REFERENCES Location (Location_ID)
);

CREATE TABLE Profiles (
Profile_ID INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT REFERENCES Profiles_Tags (Profile_ID),
OFF/ON INTEGER DEFAULT NULL,
Desc TEXT(130) DEFAULT NULL,
Public/Private INTEGER NOT NULL ,
User_ID INTEGER NOT NULL ,
User_Nr NUMERIC NOT NULL ,
User_Name TEXT NOT NULL ,
Event_ID_Events INTEGER NOT NULL  REFERENCES Events (Event_ID)
);

CREATE TABLE Profiles_Tags (
Profile_ID INTEGER NOT NULL ,
Tags_ID INTEGER NOT NULL  REFERENCES Tags (Tag_ID),
PRIMARY KEY (Profile_ID, Tags_ID)
);

CREATE TABLE Actions (
Action_ID INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
Alert_ID_Alerts NUMERIC NOT NULL  REFERENCES Alert (Alert_ID) REFERENCES Alert (Alert_ID),
Wi-Fi(ON/OFF) INTEGER NOT NULL ,
GPS(ON/OFF) INTEGER NOT NULL 
);

CREATE TABLE Tags (
Tag_ID INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
Tag TEXT(25) NOT NULL 
);

CREATE TABLE Location (
Location_ID INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
Lon REAL NOT NULL ,
Lat REAL NOT NULL 
);

CREATE TABLE Alert (
Alert_ID NUMERIC NOT NULL  PRIMARY KEY AUTOINCREMENT,
Title TEXT(25) NOT NULL ,
Volume INTEGER NOT NULL ,
Vibrator NUMERIC NOT NULL 
);

CREATE TABLE Bookmarks (
Bookmark_ID INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
Profile_ID INTEGER NOT NULL  REFERENCES Profiles (Profile_ID),
Date_Time TEXT NOT NULL  DEFAULT 'NULL'
);


